production:
#overwritten by heroku on prod

development:
  adapter: mysql2  
  encoding: utf8
  database: quotezip
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2  
  encoding: utf8
  database: quotezip_test
  pool: 5
  username: root
  password: root
  host: localhost