production:
  # adapter:
  # database:
  # pool: 5
  # timeout: 5000

development:
  adapter: mysql2  
  encoding: utf8
  database: quotezip
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2  
  encoding: utf8
  database: quotezip
  pool: 5
  username: root
  password: root
  host: localhost