production:
#overwritten by heroku on prod

development:
  adapter: mysql2  
  encoding: utf8
  database: quotezip
  pool: 5
  username: vagrant
  password: vagrant
  host: 127.0.0.1

test:
  adapter: mysql2  
  encoding: utf8
  database: quotezip_test
  pool: 5
  username: vagrant
  password: vagrant
  host: 127.0.0.1


# CREATE USER 'vagrant'@'localhost' IDENTIFIED BY 'vagrant';
# GRANT ALL PRIVILEGES ON *.* TO 'vagrant'@'localhost';
