production:
#overwritten by heroku on prod

development:
  adapter: mysql2
  encoding: utf8
  database: quoteApp_development
  pool: 5
  username: vagrant
  password: vagrant
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  database: quoteApp_test
  pool: 5
  username: vagrant
  password: vagrant
  host: 127.0.0.1
